# Generated by Django 5.2 on 2025-04-03 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.BigIntegerField()),
                ('updated_at', models.BigIntegerField()),
                ('company_name', models.CharField(max_length=255)),
                ('sort_name', models.CharField(max_length=100)),
                ('company_type', models.CharField(max_length=100)),
                ('GSTIN', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('company_email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.CharField(max_length=15, unique=True)),
                ('company_logo', models.CharField(blank=True, max_length=250, null=True)),
                ('co_token', models.CharField(blank=True, max_length=255, unique=True)),
                ('address', models.TextField()),
                ('main_role_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='RoleMaster',
            fields=[
                ('subrole_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_master', models.IntegerField()),
                ('sub_role', models.CharField(max_length=255)),
                ('subrole_url', models.CharField(max_length=255)),
                ('main_role_id', models.IntegerField()),
                ('main_role', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'base_rolemaster',
            },
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.BigIntegerField()),
                ('updated_at', models.BigIntegerField()),
                ('user_type', models.CharField(max_length=100)),
                ('user_id', models.CharField(max_length=100)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_type_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_type_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.BigIntegerField()),
                ('updated_at', models.BigIntegerField()),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('unique_username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('mobile_number', models.CharField(blank=True, max_length=13, null=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('assign_role', models.CharField(max_length=250, null=True)),
                ('auth_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('company_master', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kariotar_auth.companymaster')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_profile_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_profile_updated', to=settings.AUTH_USER_MODEL)),
                ('user_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kariotar_auth.usertype')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
