# Generated by Django 5.2 on 2025-04-03 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kariotar_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rolemaster',
            options={'ordering': ['subrole_id']},
        ),
        migrations.AlterModelTable(
            name='rolemaster',
            table=None,
        ),
    ]
