# Generated by Django 5.2 on 2025-04-03 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kariotar_auth', '0002_alter_rolemaster_options_alter_rolemaster_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RoleMaster',
            new_name='MenuMaster',
        ),
    ]
