# Generated by Django 5.2 on 2025-04-03 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kariotar_auth', '0003_rename_rolemaster_menumaster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companymaster',
            name='main_role_id',
            field=models.CharField(blank=True, null=True),
        ),
    ]
