# Generated by Django 5.2 on 2025-04-05 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kariotar_auth', '0004_alter_companymaster_main_role_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='companymaster',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usermaster',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='companymaster',
            name='company_type',
            field=models.CharField(choices=[('Private Limited Company (Ltd / LLC)', 'Private Limited Company (Ltd / LLC)'), ('Sole Proprietorship', 'Sole Proprietorship'), ('Partnership (General & Limited)', 'Partnership (General & Limited)'), ('Public Limited Company (PLC)', 'Public Limited Company (PLC)'), ('One-Person Company (OPC)', 'One-Person Company (OPC)'), ('Non-Profit Organization (NPO) / NGO', 'Non-Profit Organization (NPO) / NGO'), ('Cooperative Society', 'Cooperative Society'), ('Joint Venture (JV)', 'Joint Venture (JV)'), ('Government-Owned Company (Public Sector)', 'Government-Owned Company (Public Sector)'), ('Multinational Corporation (MNC)', 'Multinational Corporation (MNC)')], max_length=100),
        ),
    ]
