# Generated by Django 5.2 on 2025-04-05 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kariotar_auth', '0005_companymaster_is_active_usermaster_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertype',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
