# Generated by Django 5.2 on 2025-04-06 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kariotar_auth', '0006_usertype_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermaster',
            name='middle_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
