# Generated by Django 5.2 on 2025-04-15 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kariotar_auth', '0007_usermaster_middle_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertype',
            old_name='user_id',
            new_name='type_code',
        ),
    ]
