# Generated by Django 5.2 on 2025-04-06 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kariotar_auth', '0007_usermaster_middle_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('emp_name', models.CharField(max_length=255)),
                ('emp_code', models.CharField(max_length=255)),
                ('group', models.CharField(max_length=255)),
                ('emp_type', models.CharField(choices=[('Full-Time', 'Full-Time'), ('Part-Time', 'Part-Time'), ('Contract', 'Contract'), ('Intern', 'Intern'), ('Freelancer', 'Freelancer'), ('Temporary', 'Temporary'), ('Consultant', 'Consultant'), ('Apprentice', 'Apprentice'), ('Volunteer', 'Volunteer'), ('Seasonal', 'Seasonal'), ('Probationary', 'Probationary'), ('Remote', 'Remote')], max_length=20)),
                ('department', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('salary_lpa', models.BigIntegerField(default=0)),
                ('date_joined', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('offer_letter', models.CharField(blank=True, max_length=255, null=True)),
                ('emp_agreement', models.CharField(blank=True, max_length=255, null=True)),
                ('nda', models.CharField(blank=True, max_length=255, null=True)),
                ('resignation', models.CharField(blank=True, max_length=255, null=True)),
                ('assets', models.TextField(blank=True, null=True)),
                ('admin_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_employees', to='kariotar_auth.usermaster')),
                ('company_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kariotar_auth.companymaster')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees_created', to=settings.AUTH_USER_MODEL)),
                ('funt_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='functional_employees', to='kariotar_auth.usermaster')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees_updated', to=settings.AUTH_USER_MODEL)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_records', to=settings.AUTH_USER_MODEL)),
                ('user_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='kariotar_auth.usermaster')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
