# Generated by Django 5.2 on 2025-04-16 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompanEazy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empattendance',
            name='date',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
    ]
