# Generated by Django 5.2 on 2025-04-06 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompanEazy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('emp_name', models.CharField(max_length=255)),
                ('emp_code', models.CharField(max_length=50, unique=True)),
                ('personal_mobile', models.CharField(max_length=15, unique=True)),
                ('personal_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=10, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Transgender', 'Transgender'), ('Non-Binary', 'Non-Binary'), ('Genderfluid', 'Genderfluid'), ('Agender', 'Agender'), ('Two-Spirit', 'Two-Spirit'), ('Other', 'Other'), ('Prefer not to say', 'Prefer not to say')], max_length=30)),
                ('pan', models.CharField(max_length=20, unique=True)),
                ('pan_img', models.CharField(blank=True, max_length=255, null=True)),
                ('aadhar', models.CharField(max_length=20, unique=True)),
                ('aadhar_img', models.CharField(blank=True, max_length=255, null=True)),
                ('bank_name', models.CharField(max_length=255)),
                ('bank_acc_no', models.CharField(max_length=80, unique=True)),
                ('bank_ifsc', models.CharField(max_length=30)),
                ('bank_img', models.CharField(blank=True, max_length=255, null=True)),
                ('pf_acc', models.CharField(blank=True, max_length=50, null=True)),
                ('uan_acc', models.CharField(blank=True, max_length=50, null=True)),
                ('insurance_meta_data', models.JSONField(blank=True, null=True)),
                ('verified_status', models.CharField(blank=True, max_length=20, null=True)),
                ('emergency_mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('emergency_contact_relation', models.CharField(blank=True, max_length=150, null=True)),
                ('current_address', models.TextField(blank=True, null=True)),
                ('current_city', models.CharField(blank=True, max_length=100, null=True)),
                ('current_state', models.CharField(blank=True, max_length=100, null=True)),
                ('current_pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('permanent_address', models.TextField(blank=True, null=True)),
                ('permanent_city', models.CharField(blank=True, max_length=100, null=True)),
                ('permanent_state', models.CharField(blank=True, max_length=100, null=True)),
                ('permanent_pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('marital_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed'), ('Separated', 'Separated'), ('Engaged', 'Engaged'), ('In a Relationship', 'In a Relationship'), ('Complicated', 'Complicated')], max_length=20)),
                ('profile_links', models.JSONField(blank=True, null=True)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_id', to='CompanEazy.employee')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_id', to=settings.AUTH_USER_MODEL)),
                ('user_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_master_id', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
