# Generated by Django 5.2 on 2025-04-16 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompanEazy', '0002_empattendance_date'),
        ('kariotar_auth', '0008_rename_user_id_usertype_type_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empattendance',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usermasterid', to='kariotar_auth.usermaster'),
        ),
    ]
