# Generated by Django 5.2 on 2025-04-06 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CompanEazy', '0002_empprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='empprofile',
            old_name='employee_id',
            new_name='employee',
        ),
        migrations.RenameField(
            model_name='empprofile',
            old_name='user_id',
            new_name='user',
        ),
    ]
