# Generated by Django 5.2 on 2025-04-19 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompanEazy', '0003_alter_empattendance_approved_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='empattendance',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empattendance',
            name='status',
            field=models.CharField(choices=[('Absent', 'Absent'), ('Present-Office', 'Present-Office'), ('Present-Home', 'Present-Home'), ('Leave-Full-Day', 'Leave-Full-Day'), ('Leave-Half-Day', 'Leave-Half-Day'), ('Festival-&-Flexi-Holiday', 'Festival-&-Flexi-Holiday'), ('Shift-One', 'Shift-One'), ('Shift-Two', 'Shift-Two'), ('Week-Off', 'Week-Off'), ('Special-Granted-Conditional-Leave', 'Special-Granted-Conditional-Leave'), ('Present-Business-Tour', 'Present-Business-Tour')], default='Absent', max_length=90),
        ),
    ]
