# Generated by Django 5.2 on 2025-04-07 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompanEazy', '0003_rename_user_id_employee_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='office_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='office_mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
