# Generated by Django 5.2 on 2025-04-07 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompanEazy', '0004_employee_office_email_employee_office_mobile'),
        ('kariotar_auth', '0007_usermaster_middle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='empprofile',
            name='company_master',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='kariotar_auth.companymaster'),
            preserve_default=False,
        ),
    ]
