# Generated by Django 5.2 on 2025-04-08 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompanEazy', '0005_empprofile_company_master'),
    ]

    operations = [
        migrations.AddField(
            model_name='empprofile',
            name='emp_img',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
