# Generated by Django 5.2 on 2025-04-08 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompanEazy', '0006_empprofile_emp_img'),
        ('kariotar_auth', '0007_usermaster_middle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empprofile',
            name='user_master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_master_id', to='kariotar_auth.usermaster'),
        ),
    ]
