# Generated by Django 5.2 on 2025-04-08 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompanEazy', '0007_alter_empprofile_user_master'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empprofile',
            name='bank_acc_no',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
