# Generated by Django 5.2 on 2025-04-08 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompanEazy', '0008_alter_empprofile_bank_acc_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empprofile',
            name='aadhar',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='empprofile',
            name='pan',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='empprofile',
            name='personal_mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
