# Generated by Django 5.2 on 2025-04-08 16:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompanEazy', '0009_alter_empprofile_aadhar_alter_empprofile_pan_and_more'),
        ('kariotar_auth', '0007_usermaster_middle_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('emp_name', models.CharField(max_length=255)),
                ('emp_code', models.CharField(max_length=50, unique=True)),
                ('ssc_grade', models.CharField(blank=True, max_length=20, null=True)),
                ('ssc_img', models.CharField(blank=True, max_length=255, null=True)),
                ('hsc_grade', models.CharField(blank=True, max_length=20, null=True)),
                ('hsc_img', models.CharField(blank=True, max_length=255, null=True)),
                ('ug_grade', models.CharField(blank=True, max_length=20, null=True)),
                ('ug_img', models.CharField(blank=True, max_length=255, null=True)),
                ('pg_grade', models.CharField(blank=True, max_length=20, null=True)),
                ('pg_img', models.CharField(blank=True, max_length=255, null=True)),
                ('other1_name', models.CharField(blank=True, max_length=100, null=True)),
                ('other1_grade', models.CharField(blank=True, max_length=20, null=True)),
                ('other1_img', models.CharField(blank=True, max_length=255, null=True)),
                ('other2_name', models.CharField(blank=True, max_length=100, null=True)),
                ('other2_grade', models.CharField(blank=True, max_length=20, null=True)),
                ('other2_img', models.CharField(blank=True, max_length=255, null=True)),
                ('verified_status', models.CharField(blank=True, max_length=50, null=True)),
                ('company_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kariotar_auth.companymaster')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='CompanEazy.employee')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emp_educations', to=settings.AUTH_USER_MODEL)),
                ('user_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emp_educations', to='kariotar_auth.usermaster')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
