# Generated by Django 5.2 on 2025-04-15 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompanEazy', '0010_empeducation'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='resignation_dt',
            field=models.DateField(blank=True, null=True),
        ),
    ]
