# Generated by Django 5.2 on 2025-04-15 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompanEazy', '0011_employee_resignation_dt'),
    ]

    operations = [
        migrations.AddField(
            model_name='empeducation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
