# Generated by Django 5.2 on 2025-04-15 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompanEazy', '0012_empeducation_is_active'),
        ('kariotar_auth', '0008_rename_user_id_usertype_type_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('emp_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Absent', 'Absent'), ('Present-Office', 'Present - Office'), ('Present-Home', 'Present - Home'), ('Leave-Full Day', 'Leave - Full Day'), ('Leave-Half Day', 'Leave - Half Day'), ('Festival & Flexi Holiday', 'Festival & Flexi Holiday'), ('Shift One', 'Shift One'), ('Shift Two', 'Shift Two'), ('Special Granted Conditional Leave', 'Special Granted Conditional Leave'), ('Present-Business Tour', 'Present - Business Tour')], default='Absent', max_length=90)),
                ('check_in', models.BigIntegerField(blank=True, null=True)),
                ('check_in_cords', models.CharField(blank=True, max_length=100, null=True)),
                ('check_in_ip', models.CharField(blank=True, max_length=100, null=True)),
                ('check_out', models.BigIntegerField(blank=True, null=True)),
                ('check_out_cords', models.CharField(blank=True, max_length=100, null=True)),
                ('check_out_ip', models.CharField(blank=True, max_length=100, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usermasterid', to='kariotar_auth.usermaster')),
                ('company_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kariotar_auth.companymaster')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emp_id', to='CompanEazy.employee')),
                ('user_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usermaster_id', to='kariotar_auth.usermaster')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
